# This docker-compose file spins up containers for kafka, zookeeper, and the receptor controller

version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_SERVER_ID=1
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://kafka:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_MAX_REQUEST_SIZE=1048576
  gateway:
    build:
      context: ./
      dockerfile: ./cmd/gateway/Dockerfile
    image: platform-receptor-controller-gateway
    ports:
      - 8080:8080 # websocket gateway
      - 9090:9090 # gateway management server
    environment:
      - PLACEHOLDER_ENV_VAR=placeholder_env_var
    depends_on:
      - kafka
  job-receiver:
    build:
      context: ./
      dockerfile: ./cmd/job_receiver/Dockerfile
    image: platform-receptor-controller-job-receiver
    ports:
      - 8081:8081 # job_receiver management server
    environment:
      - PLACEHOLDER_ENV_VAR=placeholder_env_var
    depends_on:
      - kafka
