{
 "title": "Receptor-Controller",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "content": "<center><h1>Receptor Gateway</h1></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "content": "<center><h1>Receptor Switch</h1></center>"
  },
  {
   "title": "Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{app=\"receptor-gateway\", name=\"receptor-gateway\", kubernetes_namespace=~\"receptor-.*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"receptor-gateway\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{app=\"receptor-switch\", name=\"receptor-switch\", kubernetes_namespace=~\"receptor-.*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"receptor-switch\"}[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Websocket Messages Sent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(receptor_controller_websocket_total_messages_sent_count[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Websocket Messages Received",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(receptor_controller_websocket_total_messages_received_count[$__range]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"receptor-switch\"}[1m])"
    }
   ]
  },
  {
   "title": "Total Websocket Connections (Active + Inactive)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(receptor_controller_websocket_total_connection_count)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Websocket Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(receptor_controller_websocket_active_connection_count)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"receptor-gateway\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"receptor-switch\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"receptor-gateway\"}"
    }
   ]
  },
  {
   "title": "Incoming Response Rate [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(receptor_controller_payload_message_sizes_count[1m]))"
    }
   ]
  },
  {
   "title": "Active Websocket Connection Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "receptor_controller_websocket_active_connection_count"
    }
   ]
  },
  {
   "title": "Average Incoming Response Size [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(receptor_controller_payload_message_sizes_sum[1m]) / rate(receptor_controller_payload_message_sizes_count[1m])"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "avg(increase(receptor_controller_payload_message_sizes_bucket[1m])) by (le)"
    }
   ]
  },
  {
   "title": "Kafka Response Writer Go Routine Metrics - 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(receptor_controller_kafka_response_writer_go_routine_count[5m])",
     "legendFormat": "avg"
    },
    {
     "expr": "max_over_time(receptor_controller_kafka_response_writer_go_routine_count[5m])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Kafka Response Writer Failure Count - 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(receptor_controller_kafka_response_writer_failure_count[1m]))"
    }
   ]
  },
  {
   "title": "Websocket Messages Received - 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(receptor_controller_websocket_total_messages_received_count[1m]))"
    }
   ]
  },
  {
   "title": "Websocket Messages Sent - 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(receptor_controller_websocket_total_messages_sent_count[1m]))"
    }
   ]
  },
  {
   "title": "Receptor Responses Count - 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(receptor_controller_response_message_handled_count[1m])) + sum(increase(receptor_controller_response_message_without_handler_count[1m]))"
    }
   ]
  },
  {
   "title": "Total Websocket Connection Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(receptor_controller_websocket_total_connection_count)"
    }
   ]
  },
  {
   "title": "Duplicate Websocket Connection Attempts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=\"redis\", namespace=~\"receptor-.*\"}[5m])",
     "legendFormat": "{{pod_name}}:{{container_name}}"
    }
   ]
  },
  {
   "title": "Percentage of CPU limit consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"receptor-.*\",container_name=\"redis\"}[5m])) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"receptor-.*\", container=\"redis\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=~\"receptor-.*\",container_name=\"redis\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Percentage of memory limit consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"receptor-.*\",container_name=\"redis\"}) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"receptor-.*\",container=\"redis\"})"
    }
   ]
  }
 ]
}